services:
  - type: web
    name: skymanager-api
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: DTE_AMBIENTE
        value: "00"
      - key: DTE_NIT
        sync: false
      - key: DTE_NRC
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: BREVO_FROM_NAME
        value: Acajutla Airlines
      - key: CORS_ORIGIN
        sync: false
  - type: static
    name: skymanager-backoffice
    rootDir: frontend-backoffice
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html